//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomipro.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Control_Pago()
        {
            this.Nominas = new HashSet<Nomina>();
        }
    
        public int ID_Control_Pago { get; set; }
        public Nullable<int> ID_EmpleCP { get; set; }
        public Nullable<int> Valor_Horas_Extras { get; set; }
        public Nullable<int> Valor_Parafiscal { get; set; }
        public string Mes { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nomina> Nominas { get; set; }
    }
}
