//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomipro.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Control_Pago = new HashSet<Control_Pago>();
            this.HExtraxEmpleadoes = new HashSet<HExtraxEmpleado>();
            this.Nominas = new HashSet<Nomina>();
            this.ParaxEmples = new HashSet<ParaxEmple>();
        }
    
        public int ID_Emple { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Correo { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Tipo_Documento { get; set; }
        public Nullable<int> Numero_Documento { get; set; }
        public Nullable<int> ID_Cargo { get; set; }
        public Nullable<int> ID_Vinculacion { get; set; }
        public Nullable<int> ID_Horario { get; set; }
        public string Estado { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Control_Pago> Control_Pago { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Tipo_vinculacion Tipo_vinculacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HExtraxEmpleado> HExtraxEmpleadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nomina> Nominas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParaxEmple> ParaxEmples { get; set; }
    }
}
