//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomipro.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horas_Extras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horas_Extras()
        {
            this.HExtraxEmpleadoes = new HashSet<HExtraxEmpleado>();
        }
    
        public int ID_Hextras { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Valor { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HExtraxEmpleado> HExtraxEmpleadoes { get; set; }
    }
}
