

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nomipro.ModelDB
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class NomiproEntities : DbContext
{
    public NomiproEntities()
        : base("name=NomiproEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Cargo> Cargos { get; set; }

    public virtual DbSet<Control_Pago> Control_Pago { get; set; }

    public virtual DbSet<Empleado> Empleados { get; set; }

    public virtual DbSet<HExtraxEmpleado> HExtraxEmpleadoes { get; set; }

    public virtual DbSet<Horario> Horarios { get; set; }

    public virtual DbSet<Horas_Extras> Horas_Extras { get; set; }

    public virtual DbSet<Nomina> Nominas { get; set; }

    public virtual DbSet<Parafiscale> Parafiscales { get; set; }

    public virtual DbSet<ParaxEmple> ParaxEmples { get; set; }

    public virtual DbSet<Tipo_vinculacion> Tipo_vinculacion { get; set; }

}

}

